#!/usr/bin/env perl
use strict;
use Bio::SeqIO;

my $usage  = "./waiting_time < fastafile symbol";
my $symbol = shift() or die("Usage: $usage $!");

my $instream = Bio::SeqIO->new( -fh => \*STDIN, -format => 'Fasta' );
my $written = 0;
printf("times <- c(");
while( my $seq = $instream->next_seq )
{
  my $waiting_time = index($seq->seq, $symbol);
  if(not $written)
  {
    $written++;
  }
  else
  {
    printf(", ");
  }
  printf("%d", $waiting_time + length($symbol)) if($waiting_time >= 0);
}
printf(")\n");
